# Generated by Django 2.2 on 2019-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('abstract', models.TextField(verbose_name='Resumo')),
                ('year_beg', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('paper', models.FileField(upload_to='papers/')),
            ],
        ),
    ]
