# Generated by Django 2.2 on 2019-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('type', models.IntegerField(choices=[('0', 'Conferência'), ('1', 'Periódico'), ('2', 'Resumo')])),
                ('bibtex', models.FileField(upload_to='publications/')),
            ],
        ),
    ]
