# Generated by Django 2.2 on 2019-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='name',
        ),
        migrations.AlterField(
            model_name='professor',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='room',
            field=models.CharField(max_length=50, verbose_name='Sala'),
        ),
    ]
