# Generated by Django 2.2 on 2019-05-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.IntegerField(choices=[(0, 'Graduação'), (1, 'Mestrado'), (2, 'Doutorado'), (3, 'Pós-doutorado')]),
        ),
    ]
