# Generated by Django 2.2 on 2019-05-31 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Disciplina')),
                ('type', models.IntegerField(choices=[('0', 'Graduação'), ('1', 'Pós-graduação')])),
            ],
        ),
        migrations.CreateModel(
            name='SubjectContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='contents/')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subject.Subject')),
            ],
        ),
    ]
