# Generated by Django 2.2 on 2019-05-31 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subjectcontent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.IntegerField(choices=[(0, 'Graduação'), (1, 'Pós-graduação')]),
        ),
        migrations.AlterField(
            model_name='subjectcontent',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contents', to='subject.Subject'),
        ),
    ]
