# Generated by Django 2.2 on 2019-04-26 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='contents/')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='class.Class')),
            ],
        ),
    ]
